package com.goodsoft.society_zy.domain.entity.hospital;

import java.util.Objects;

/**
 * 就医信息实体
 * Created by 严彬荣 on 2017/10/25.
 *
 * @version V1.0
 */
public class ConsultInfo implements java.io.Serializable {
    private static final long serialVersionUID = -5172744192766740640L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.BH
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.XM
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.XB
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.CSRQ
     */
    private String csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.NL
     */
    private String nl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.SFZH
     */
    private String sfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.ZY
     */
    private String zy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.HJQH
     */
    private String hjqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.XZZ
     */
    private String xzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.GZDW
     */
    private String gzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.GZDWDH
     */
    private String gzdwdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.ZYLXR
     */
    private String zylxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.LXRDZ
     */
    private String lxrdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.LXDH
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.JZRQ
     */
    private String jzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.RYRQ
     */
    private String ryrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.CYRQ
     */
    private String cyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.JZYY
     */
    private String jzyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.JZKS
     */
    private String jzks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.ZZYS
     */
    private String zzys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.SSXQ
     */
    private String ssxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.XGR
     */
    private String xgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.XGSJ
     */
    private String xgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_YY_JYXX.RJSJ
     */
    private String rjsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.BH
     *
     * @return the value of T_SHZY_YY_JYXX.BH
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.BH
     *
     * @param bh the value for T_SHZY_YY_JYXX.BH
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.XM
     *
     * @return the value of T_SHZY_YY_JYXX.XM
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.XM
     *
     * @param xm the value for T_SHZY_YY_JYXX.XM
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.XB
     *
     * @return the value of T_SHZY_YY_JYXX.XB
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.XB
     *
     * @param xb the value for T_SHZY_YY_JYXX.XB
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.CSRQ
     *
     * @return the value of T_SHZY_YY_JYXX.CSRQ
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.CSRQ
     *
     * @param csrq the value for T_SHZY_YY_JYXX.CSRQ
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq == null ? null : csrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.NL
     *
     * @return the value of T_SHZY_YY_JYXX.NL
     */
    public String getNl() {
        return nl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.NL
     *
     * @param nl the value for T_SHZY_YY_JYXX.NL
     */
    public void setNl(String nl) {
        this.nl = nl == null ? null : nl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.SFZH
     *
     * @return the value of T_SHZY_YY_JYXX.SFZH
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.SFZH
     *
     * @param sfzh the value for T_SHZY_YY_JYXX.SFZH
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.ZY
     *
     * @return the value of T_SHZY_YY_JYXX.ZY
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.ZY
     *
     * @param zy the value for T_SHZY_YY_JYXX.ZY
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.HJQH
     *
     * @return the value of T_SHZY_YY_JYXX.HJQH
     */
    public String getHjqh() {
        return hjqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.HJQH
     *
     * @param hjqh the value for T_SHZY_YY_JYXX.HJQH
     */
    public void setHjqh(String hjqh) {
        this.hjqh = hjqh == null ? null : hjqh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.XZZ
     *
     * @return the value of T_SHZY_YY_JYXX.XZZ
     */
    public String getXzz() {
        return xzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.XZZ
     *
     * @param xzz the value for T_SHZY_YY_JYXX.XZZ
     */
    public void setXzz(String xzz) {
        this.xzz = xzz == null ? null : xzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.GZDW
     *
     * @return the value of T_SHZY_YY_JYXX.GZDW
     */
    public String getGzdw() {
        return gzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.GZDW
     *
     * @param gzdw the value for T_SHZY_YY_JYXX.GZDW
     */
    public void setGzdw(String gzdw) {
        this.gzdw = gzdw == null ? null : gzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.GZDWDH
     *
     * @return the value of T_SHZY_YY_JYXX.GZDWDH
     */
    public String getGzdwdh() {
        return gzdwdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.GZDWDH
     *
     * @param gzdwdh the value for T_SHZY_YY_JYXX.GZDWDH
     */
    public void setGzdwdh(String gzdwdh) {
        this.gzdwdh = gzdwdh == null ? null : gzdwdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.ZYLXR
     *
     * @return the value of T_SHZY_YY_JYXX.ZYLXR
     */
    public String getZylxr() {
        return zylxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.ZYLXR
     *
     * @param zylxr the value for T_SHZY_YY_JYXX.ZYLXR
     */
    public void setZylxr(String zylxr) {
        this.zylxr = zylxr == null ? null : zylxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.LXRDZ
     *
     * @return the value of T_SHZY_YY_JYXX.LXRDZ
     */
    public String getLxrdz() {
        return lxrdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.LXRDZ
     *
     * @param lxrdz the value for T_SHZY_YY_JYXX.LXRDZ
     */
    public void setLxrdz(String lxrdz) {
        this.lxrdz = lxrdz == null ? null : lxrdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.LXDH
     *
     * @return the value of T_SHZY_YY_JYXX.LXDH
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.LXDH
     *
     * @param lxdh the value for T_SHZY_YY_JYXX.LXDH
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.JZRQ
     *
     * @return the value of T_SHZY_YY_JYXX.JZRQ
     */
    public String getJzrq() {
        return jzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.JZRQ
     *
     * @param jzrq the value for T_SHZY_YY_JYXX.JZRQ
     */
    public void setJzrq(String jzrq) {
        this.jzrq = jzrq == null ? null : jzrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.RYRQ
     *
     * @return the value of T_SHZY_YY_JYXX.RYRQ
     */
    public String getRyrq() {
        return ryrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.RYRQ
     *
     * @param ryrq the value for T_SHZY_YY_JYXX.RYRQ
     */
    public void setRyrq(String ryrq) {
        this.ryrq = ryrq == null ? null : ryrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.CYRQ
     *
     * @return the value of T_SHZY_YY_JYXX.CYRQ
     */
    public String getCyrq() {
        return cyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.CYRQ
     *
     * @param cyrq the value for T_SHZY_YY_JYXX.CYRQ
     */
    public void setCyrq(String cyrq) {
        this.cyrq = cyrq == null ? null : cyrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.JZYY
     *
     * @return the value of T_SHZY_YY_JYXX.JZYY
     */
    public String getJzyy() {
        return jzyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.JZYY
     *
     * @param jzyy the value for T_SHZY_YY_JYXX.JZYY
     */
    public void setJzyy(String jzyy) {
        this.jzyy = jzyy == null ? null : jzyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.JZKS
     *
     * @return the value of T_SHZY_YY_JYXX.JZKS
     */
    public String getJzks() {
        return jzks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.JZKS
     *
     * @param jzks the value for T_SHZY_YY_JYXX.JZKS
     */
    public void setJzks(String jzks) {
        this.jzks = jzks == null ? null : jzks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.ZZYS
     *
     * @return the value of T_SHZY_YY_JYXX.ZZYS
     */
    public String getZzys() {
        return zzys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.ZZYS
     *
     * @param zzys the value for T_SHZY_YY_JYXX.ZZYS
     */
    public void setZzys(String zzys) {
        this.zzys = zzys == null ? null : zzys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.SSXQ
     *
     * @return the value of T_SHZY_YY_JYXX.SSXQ
     */
    public String getSsxq() {
        return ssxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.SSXQ
     *
     * @param ssxq the value for T_SHZY_YY_JYXX.SSXQ
     */
    public void setSsxq(String ssxq) {
        this.ssxq = ssxq == null ? null : ssxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.XGR
     *
     * @return the value of T_SHZY_YY_JYXX.XGR
     */
    public String getXgr() {
        return xgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.XGR
     *
     * @param xgr the value for T_SHZY_YY_JYXX.XGR
     */
    public void setXgr(String xgr) {
        this.xgr = xgr == null ? null : xgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.XGSJ
     *
     * @return the value of T_SHZY_YY_JYXX.XGSJ
     */
    public String getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.XGSJ
     *
     * @param xgsj the value for T_SHZY_YY_JYXX.XGSJ
     */
    public void setXgsj(String xgsj) {
        this.xgsj = xgsj == null ? null : xgsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_YY_JYXX.RJSJ
     *
     * @return the value of T_SHZY_YY_JYXX.RJSJ
     */
    public String getRjsj() {
        return rjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_YY_JYXX.RJSJ
     *
     * @param rjsj the value for T_SHZY_YY_JYXX.RJSJ
     */
    public void setRjsj(String rjsj) {
        this.rjsj = rjsj == null ? null : rjsj.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ConsultInfo)) return false;
        ConsultInfo that = (ConsultInfo) o;
        return Objects.equals(bh, that.bh) &&
                Objects.equals(xm, that.xm) &&
                Objects.equals(xb, that.xb) &&
                Objects.equals(csrq, that.csrq) &&
                Objects.equals(nl, that.nl) &&
                Objects.equals(sfzh, that.sfzh) &&
                Objects.equals(zy, that.zy) &&
                Objects.equals(hjqh, that.hjqh) &&
                Objects.equals(xzz, that.xzz) &&
                Objects.equals(gzdw, that.gzdw) &&
                Objects.equals(gzdwdh, that.gzdwdh) &&
                Objects.equals(zylxr, that.zylxr) &&
                Objects.equals(lxrdz, that.lxrdz) &&
                Objects.equals(lxdh, that.lxdh) &&
                Objects.equals(jzrq, that.jzrq) &&
                Objects.equals(ryrq, that.ryrq) &&
                Objects.equals(cyrq, that.cyrq) &&
                Objects.equals(jzyy, that.jzyy) &&
                Objects.equals(jzks, that.jzks) &&
                Objects.equals(zzys, that.zzys) &&
                Objects.equals(ssxq, that.ssxq) &&
                Objects.equals(xgr, that.xgr) &&
                Objects.equals(xgsj, that.xgsj) &&
                Objects.equals(rjsj, that.rjsj);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bh, xm, xb, csrq, nl, sfzh, zy, hjqh, xzz, gzdw, gzdwdh, zylxr, lxrdz, lxdh, jzrq, ryrq, cyrq, jzyy, jzks, zzys, ssxq, xgr, xgsj, rjsj);
    }
}
