package com.goodsoft.society_zy.domain.entity.hospital;

import java.util.Objects;

/**
 * 医务人员实体
 * Created by 严彬荣 on 2017/10/25.
 *
 * @version V1.0
 */
public class MedicalStaffInfo implements java.io.Serializable {
    private static final long serialVersionUID = 7863640340618618970L;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.BH
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.XM
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.SFZH
     */
    private String sfzh;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.XB
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.MZ
     */
    private String mz;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.XZZ
     */
    private String xzz;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.HJD
     */
    private String hjd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.SJHM
     */
    private String sjhm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.GZ
     */
    private String gz;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.SSXQ
     */
    private String ssxq;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.XGR
     */
    private String xgr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.XGSJ
     */
    private String xgsj;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column T_SHZY_YY_YWRY.RKSJ
     */
    private String rksj;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.BH
     *
     * @return the value of T_SHZY_YY_YWRY.BH
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.BH
     *
     * @param bh the value for T_SHZY_YY_YWRY.BH
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.XM
     *
     * @return the value of T_SHZY_YY_YWRY.XM
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.XM
     *
     * @param xm the value for T_SHZY_YY_YWRY.XM
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.SFZH
     *
     * @return the value of T_SHZY_YY_YWRY.SFZH
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.SFZH
     *
     * @param sfzh the value for T_SHZY_YY_YWRY.SFZH
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.XB
     *
     * @return the value of T_SHZY_YY_YWRY.XB
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.XB
     *
     * @param xb the value for T_SHZY_YY_YWRY.XB
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.MZ
     *
     * @return the value of T_SHZY_YY_YWRY.MZ
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.MZ
     *
     * @param mz the value for T_SHZY_YY_YWRY.MZ
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.XZZ
     *
     * @return the value of T_SHZY_YY_YWRY.XZZ
     */
    public String getXzz() {
        return xzz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.XZZ
     *
     * @param xzz the value for T_SHZY_YY_YWRY.XZZ
     */
    public void setXzz(String xzz) {
        this.xzz = xzz == null ? null : xzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.HJD
     *
     * @return the value of T_SHZY_YY_YWRY.HJD
     */
    public String getHjd() {
        return hjd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.HJD
     *
     * @param hjd the value for T_SHZY_YY_YWRY.HJD
     */
    public void setHjd(String hjd) {
        this.hjd = hjd == null ? null : hjd.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.SJHM
     *
     * @return the value of T_SHZY_YY_YWRY.SJHM
     */
    public String getSjhm() {
        return sjhm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.SJHM
     *
     * @param sjhm the value for T_SHZY_YY_YWRY.SJHM
     */
    public void setSjhm(String sjhm) {
        this.sjhm = sjhm == null ? null : sjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.GZ
     *
     * @return the value of T_SHZY_YY_YWRY.GZ
     */
    public String getGz() {
        return gz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.GZ
     *
     * @param gz the value for T_SHZY_YY_YWRY.GZ
     */
    public void setGz(String gz) {
        this.gz = gz == null ? null : gz.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.SSXQ
     *
     * @return the value of T_SHZY_YY_YWRY.SSXQ
     */
    public String getSsxq() {
        return ssxq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.SSXQ
     *
     * @param ssxq the value for T_SHZY_YY_YWRY.SSXQ
     */
    public void setSsxq(String ssxq) {
        this.ssxq = ssxq == null ? null : ssxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.XGR
     *
     * @return the value of T_SHZY_YY_YWRY.XGR
     */
    public String getXgr() {
        return xgr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.XGR
     *
     * @param xgr the value for T_SHZY_YY_YWRY.XGR
     */
    public void setXgr(String xgr) {
        this.xgr = xgr == null ? null : xgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.XGSJ
     *
     * @return the value of T_SHZY_YY_YWRY.XGSJ
     */
    public String getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.XGSJ
     *
     * @param xgsj the value for T_SHZY_YY_YWRY.XGSJ
     */
    public void setXgsj(String xgsj) {
        this.xgsj = xgsj == null ? null : xgsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column T_SHZY_YY_YWRY.RKSJ
     *
     * @return the value of T_SHZY_YY_YWRY.RKSJ
     */
    public String getRksj() {
        return rksj;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column T_SHZY_YY_YWRY.RKSJ
     *
     * @param rksj the value for T_SHZY_YY_YWRY.RKSJ
     */
    public void setRksj(String rksj) {
        this.rksj = rksj == null ? null : rksj.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof MedicalStaffInfo)) return false;
        MedicalStaffInfo that = (MedicalStaffInfo) o;
        return Objects.equals(bh, that.bh) &&
                Objects.equals(xm, that.xm) &&
                Objects.equals(sfzh, that.sfzh) &&
                Objects.equals(xb, that.xb) &&
                Objects.equals(mz, that.mz) &&
                Objects.equals(xzz, that.xzz) &&
                Objects.equals(hjd, that.hjd) &&
                Objects.equals(sjhm, that.sjhm) &&
                Objects.equals(gz, that.gz) &&
                Objects.equals(ssxq, that.ssxq) &&
                Objects.equals(xgr, that.xgr) &&
                Objects.equals(xgsj, that.xgsj) &&
                Objects.equals(rksj, that.rksj);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bh, xm, sfzh, xb, mz, xzz, hjd, sjhm, gz, ssxq, xgr, xgsj, rksj);
    }
}
