package com.goodsoft.society_zy.domain.entity.school;

import java.util.Objects;

/**
 * 描述:
 * ===>高中学生信息实体
 *
 * @author 严彬荣 Created on 2017-10-25 13:59
 * @version V1.0
 */
public class Student_advanced implements java.io.Serializable {

    private static final long serialVersionUID = -2811737952766216181L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.BH
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.XM
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.CYM
     */
    private String cym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.XB
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SFZH
     */
    private String sfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.MZ
     */
    private String mz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.RXNF
     */
    private String rxnf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.BJ
     */
    private String bj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.XX
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.XJH
     */
    private String xjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.HJDZ
     */
    private String hjdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.JTCZDXXDZ
     */
    private String jtczdxxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.ZKCJ
     */
    private String zkcj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.MQXM
     */
    private String mqxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.MQSFZH
     */
    private String mqsfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.MQGZDW
     */
    private String mqgzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.MQLXDH
     */
    private String mqlxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.FQXM
     */
    private String fqxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.FQSFZH
     */
    private String fqsfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.FQLXDH
     */
    private String fqlxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.FQGZDW
     */
    private String fqgzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SJRXM1
     */
    private String sjrxm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.GX1
     */
    private String gx1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SJRSFZH1
     */
    private String sjrsfzh1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SJRGZDW1
     */
    private String sjrgzdw1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SJRLXDG1
     */
    private String sjrlxdg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SJRXM2
     */
    private String sjrxm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.GX2
     */
    private String gx2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SJRSFZH2
     */
    private String sjrsfzh2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SJRGZDW2
     */
    private String sjrgzdw2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SJRLXDG2
     */
    private String sjrlxdg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.XJZT
     */
    private String xjzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.BZ
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.SSXQ
     */
    private String ssxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.XGR
     */
    private String xgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.XGSJ
     */
    private String xgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_GZ.RKSJ
     */
    private String rksj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.BH
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.BH
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.BH
     *
     * @param bh the value for T_SHZY_JY_XSXX_GZ.BH
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.XM
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.XM
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.XM
     *
     * @param xm the value for T_SHZY_JY_XSXX_GZ.XM
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.CYM
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.CYM
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.CYM
     *
     * @param cym the value for T_SHZY_JY_XSXX_GZ.CYM
     */
    public void setCym(String cym) {
        this.cym = cym == null ? null : cym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.XB
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.XB
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.XB
     *
     * @param xb the value for T_SHZY_JY_XSXX_GZ.XB
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SFZH
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SFZH
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SFZH
     *
     * @param sfzh the value for T_SHZY_JY_XSXX_GZ.SFZH
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.MZ
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.MZ
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.MZ
     *
     * @param mz the value for T_SHZY_JY_XSXX_GZ.MZ
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.RXNF
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.RXNF
     */
    public String getRxnf() {
        return rxnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.RXNF
     *
     * @param rxnf the value for T_SHZY_JY_XSXX_GZ.RXNF
     */
    public void setRxnf(String rxnf) {
        this.rxnf = rxnf == null ? null : rxnf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.BJ
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.BJ
     */
    public String getBj() {
        return bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.BJ
     *
     * @param bj the value for T_SHZY_JY_XSXX_GZ.BJ
     */
    public void setBj(String bj) {
        this.bj = bj == null ? null : bj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.XX
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.XX
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.XX
     *
     * @param xx the value for T_SHZY_JY_XSXX_GZ.XX
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.XJH
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.XJH
     */
    public String getXjh() {
        return xjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.XJH
     *
     * @param xjh the value for T_SHZY_JY_XSXX_GZ.XJH
     */
    public void setXjh(String xjh) {
        this.xjh = xjh == null ? null : xjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.HJDZ
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.HJDZ
     */
    public String getHjdz() {
        return hjdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.HJDZ
     *
     * @param hjdz the value for T_SHZY_JY_XSXX_GZ.HJDZ
     */
    public void setHjdz(String hjdz) {
        this.hjdz = hjdz == null ? null : hjdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.JTCZDXXDZ
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.JTCZDXXDZ
     */
    public String getJtczdxxdz() {
        return jtczdxxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.JTCZDXXDZ
     *
     * @param jtczdxxdz the value for T_SHZY_JY_XSXX_GZ.JTCZDXXDZ
     */
    public void setJtczdxxdz(String jtczdxxdz) {
        this.jtczdxxdz = jtczdxxdz == null ? null : jtczdxxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.ZKCJ
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.ZKCJ
     */
    public String getZkcj() {
        return zkcj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.ZKCJ
     *
     * @param zkcj the value for T_SHZY_JY_XSXX_GZ.ZKCJ
     */
    public void setZkcj(String zkcj) {
        this.zkcj = zkcj == null ? null : zkcj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.MQXM
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.MQXM
     */
    public String getMqxm() {
        return mqxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.MQXM
     *
     * @param mqxm the value for T_SHZY_JY_XSXX_GZ.MQXM
     */
    public void setMqxm(String mqxm) {
        this.mqxm = mqxm == null ? null : mqxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.MQSFZH
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.MQSFZH
     */
    public String getMqsfzh() {
        return mqsfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.MQSFZH
     *
     * @param mqsfzh the value for T_SHZY_JY_XSXX_GZ.MQSFZH
     */
    public void setMqsfzh(String mqsfzh) {
        this.mqsfzh = mqsfzh == null ? null : mqsfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.MQGZDW
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.MQGZDW
     */
    public String getMqgzdw() {
        return mqgzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.MQGZDW
     *
     * @param mqgzdw the value for T_SHZY_JY_XSXX_GZ.MQGZDW
     */
    public void setMqgzdw(String mqgzdw) {
        this.mqgzdw = mqgzdw == null ? null : mqgzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.MQLXDH
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.MQLXDH
     */
    public String getMqlxdh() {
        return mqlxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.MQLXDH
     *
     * @param mqlxdh the value for T_SHZY_JY_XSXX_GZ.MQLXDH
     */
    public void setMqlxdh(String mqlxdh) {
        this.mqlxdh = mqlxdh == null ? null : mqlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.FQXM
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.FQXM
     */
    public String getFqxm() {
        return fqxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.FQXM
     *
     * @param fqxm the value for T_SHZY_JY_XSXX_GZ.FQXM
     */
    public void setFqxm(String fqxm) {
        this.fqxm = fqxm == null ? null : fqxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.FQSFZH
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.FQSFZH
     */
    public String getFqsfzh() {
        return fqsfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.FQSFZH
     *
     * @param fqsfzh the value for T_SHZY_JY_XSXX_GZ.FQSFZH
     */
    public void setFqsfzh(String fqsfzh) {
        this.fqsfzh = fqsfzh == null ? null : fqsfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.FQLXDH
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.FQLXDH
     */
    public String getFqlxdh() {
        return fqlxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.FQLXDH
     *
     * @param fqlxdh the value for T_SHZY_JY_XSXX_GZ.FQLXDH
     */
    public void setFqlxdh(String fqlxdh) {
        this.fqlxdh = fqlxdh == null ? null : fqlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.FQGZDW
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.FQGZDW
     */
    public String getFqgzdw() {
        return fqgzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.FQGZDW
     *
     * @param fqgzdw the value for T_SHZY_JY_XSXX_GZ.FQGZDW
     */
    public void setFqgzdw(String fqgzdw) {
        this.fqgzdw = fqgzdw == null ? null : fqgzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SJRXM1
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SJRXM1
     */
    public String getSjrxm1() {
        return sjrxm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SJRXM1
     *
     * @param sjrxm1 the value for T_SHZY_JY_XSXX_GZ.SJRXM1
     */
    public void setSjrxm1(String sjrxm1) {
        this.sjrxm1 = sjrxm1 == null ? null : sjrxm1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.GX1
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.GX1
     */
    public String getGx1() {
        return gx1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.GX1
     *
     * @param gx1 the value for T_SHZY_JY_XSXX_GZ.GX1
     */
    public void setGx1(String gx1) {
        this.gx1 = gx1 == null ? null : gx1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SJRSFZH1
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SJRSFZH1
     */
    public String getSjrsfzh1() {
        return sjrsfzh1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SJRSFZH1
     *
     * @param sjrsfzh1 the value for T_SHZY_JY_XSXX_GZ.SJRSFZH1
     */
    public void setSjrsfzh1(String sjrsfzh1) {
        this.sjrsfzh1 = sjrsfzh1 == null ? null : sjrsfzh1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SJRGZDW1
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SJRGZDW1
     */
    public String getSjrgzdw1() {
        return sjrgzdw1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SJRGZDW1
     *
     * @param sjrgzdw1 the value for T_SHZY_JY_XSXX_GZ.SJRGZDW1
     */
    public void setSjrgzdw1(String sjrgzdw1) {
        this.sjrgzdw1 = sjrgzdw1 == null ? null : sjrgzdw1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SJRLXDG1
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SJRLXDG1
     */
    public String getSjrlxdg1() {
        return sjrlxdg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SJRLXDG1
     *
     * @param sjrlxdg1 the value for T_SHZY_JY_XSXX_GZ.SJRLXDG1
     */
    public void setSjrlxdg1(String sjrlxdg1) {
        this.sjrlxdg1 = sjrlxdg1 == null ? null : sjrlxdg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SJRXM2
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SJRXM2
     */
    public String getSjrxm2() {
        return sjrxm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SJRXM2
     *
     * @param sjrxm2 the value for T_SHZY_JY_XSXX_GZ.SJRXM2
     */
    public void setSjrxm2(String sjrxm2) {
        this.sjrxm2 = sjrxm2 == null ? null : sjrxm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.GX2
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.GX2
     */
    public String getGx2() {
        return gx2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.GX2
     *
     * @param gx2 the value for T_SHZY_JY_XSXX_GZ.GX2
     */
    public void setGx2(String gx2) {
        this.gx2 = gx2 == null ? null : gx2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SJRSFZH2
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SJRSFZH2
     */
    public String getSjrsfzh2() {
        return sjrsfzh2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SJRSFZH2
     *
     * @param sjrsfzh2 the value for T_SHZY_JY_XSXX_GZ.SJRSFZH2
     */
    public void setSjrsfzh2(String sjrsfzh2) {
        this.sjrsfzh2 = sjrsfzh2 == null ? null : sjrsfzh2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SJRGZDW2
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SJRGZDW2
     */
    public String getSjrgzdw2() {
        return sjrgzdw2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SJRGZDW2
     *
     * @param sjrgzdw2 the value for T_SHZY_JY_XSXX_GZ.SJRGZDW2
     */
    public void setSjrgzdw2(String sjrgzdw2) {
        this.sjrgzdw2 = sjrgzdw2 == null ? null : sjrgzdw2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SJRLXDG2
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SJRLXDG2
     */
    public String getSjrlxdg2() {
        return sjrlxdg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SJRLXDG2
     *
     * @param sjrlxdg2 the value for T_SHZY_JY_XSXX_GZ.SJRLXDG2
     */
    public void setSjrlxdg2(String sjrlxdg2) {
        this.sjrlxdg2 = sjrlxdg2 == null ? null : sjrlxdg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.XJZT
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.XJZT
     */
    public String getXjzt() {
        return xjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.XJZT
     *
     * @param xjzt the value for T_SHZY_JY_XSXX_GZ.XJZT
     */
    public void setXjzt(String xjzt) {
        this.xjzt = xjzt == null ? null : xjzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.BZ
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.BZ
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.BZ
     *
     * @param bz the value for T_SHZY_JY_XSXX_GZ.BZ
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.SSXQ
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.SSXQ
     */
    public String getSsxq() {
        return ssxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.SSXQ
     *
     * @param ssxq the value for T_SHZY_JY_XSXX_GZ.SSXQ
     */
    public void setSsxq(String ssxq) {
        this.ssxq = ssxq == null ? null : ssxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.XGR
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.XGR
     */
    public String getXgr() {
        return xgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.XGR
     *
     * @param xgr the value for T_SHZY_JY_XSXX_GZ.XGR
     */
    public void setXgr(String xgr) {
        this.xgr = xgr == null ? null : xgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.XGSJ
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.XGSJ
     */
    public String getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.XGSJ
     *
     * @param xgsj the value for T_SHZY_JY_XSXX_GZ.XGSJ
     */
    public void setXgsj(String xgsj) {
        this.xgsj = xgsj == null ? null : xgsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_GZ.RKSJ
     *
     * @return the value of T_SHZY_JY_XSXX_GZ.RKSJ
     */
    public String getRksj() {
        return rksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_GZ.RKSJ
     *
     * @param rksj the value for T_SHZY_JY_XSXX_GZ.RKSJ
     */
    public void setRksj(String rksj) {
        this.rksj = rksj == null ? null : rksj.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Student_advanced)) return false;
        Student_advanced that = (Student_advanced) o;
        return Objects.equals(bh, that.bh) &&
                Objects.equals(xm, that.xm) &&
                Objects.equals(cym, that.cym) &&
                Objects.equals(xb, that.xb) &&
                Objects.equals(sfzh, that.sfzh) &&
                Objects.equals(mz, that.mz) &&
                Objects.equals(rxnf, that.rxnf) &&
                Objects.equals(bj, that.bj) &&
                Objects.equals(xx, that.xx) &&
                Objects.equals(xjh, that.xjh) &&
                Objects.equals(hjdz, that.hjdz) &&
                Objects.equals(jtczdxxdz, that.jtczdxxdz) &&
                Objects.equals(zkcj, that.zkcj) &&
                Objects.equals(mqxm, that.mqxm) &&
                Objects.equals(mqsfzh, that.mqsfzh) &&
                Objects.equals(mqgzdw, that.mqgzdw) &&
                Objects.equals(mqlxdh, that.mqlxdh) &&
                Objects.equals(fqxm, that.fqxm) &&
                Objects.equals(fqsfzh, that.fqsfzh) &&
                Objects.equals(fqlxdh, that.fqlxdh) &&
                Objects.equals(fqgzdw, that.fqgzdw) &&
                Objects.equals(sjrxm1, that.sjrxm1) &&
                Objects.equals(gx1, that.gx1) &&
                Objects.equals(sjrsfzh1, that.sjrsfzh1) &&
                Objects.equals(sjrgzdw1, that.sjrgzdw1) &&
                Objects.equals(sjrlxdg1, that.sjrlxdg1) &&
                Objects.equals(sjrxm2, that.sjrxm2) &&
                Objects.equals(gx2, that.gx2) &&
                Objects.equals(sjrsfzh2, that.sjrsfzh2) &&
                Objects.equals(sjrgzdw2, that.sjrgzdw2) &&
                Objects.equals(sjrlxdg2, that.sjrlxdg2) &&
                Objects.equals(xjzt, that.xjzt) &&
                Objects.equals(bz, that.bz) &&
                Objects.equals(ssxq, that.ssxq) &&
                Objects.equals(xgr, that.xgr) &&
                Objects.equals(xgsj, that.xgsj) &&
                Objects.equals(rksj, that.rksj);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bh, xm, cym, xb, sfzh, mz, rxnf, bj, xx, xjh, hjdz, jtczdxxdz, zkcj, mqxm, mqsfzh, mqgzdw, mqlxdh, fqxm, fqsfzh, fqlxdh, fqgzdw, sjrxm1, gx1, sjrsfzh1, sjrgzdw1, sjrlxdg1, sjrxm2, gx2, sjrsfzh2, sjrgzdw2, sjrlxdg2, xjzt, bz, ssxq, xgr, xgsj, rksj);
    }
}
