package com.goodsoft.society_zy.domain.entity.school;

import java.util.Objects;

/**
 * 描述:
 * ===>初中学生信息实体
 *
 * @author 严彬荣 Created on 2017-10-25 13:58
 * @version V1.0
 */
public class Student_middle implements java.io.Serializable {

    private static final long serialVersionUID = 2354624154661717369L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.BH
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.XM
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.CYM
     */
    private String cym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.XB
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SFZH
     */
    private String sfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.MZ
     */
    private String mz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.RXNF
     */
    private String rxnf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.BJ
     */
    private String bj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.XX
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.XJH
     */
    private String xjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.XXXJH
     */
    private String xxxjh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.HJSZD
     */
    private String hjszd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.JTXXDZ
     */
    private String jtxxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.HJDJYZGBM
     */
    private String hjdjyzgbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SFGE
     */
    private String sfge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SFCJ
     */
    private String sfcj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SFJS
     */
    private String sfjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SFLSET
     */
    private String sflset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.MQXM
     */
    private String mqxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.MQSFZH
     */
    private String mqsfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.MQGZDW
     */
    private String mqgzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.MQLXDH
     */
    private String mqlxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.FQXM
     */
    private String fqxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.FQSFZH
     */
    private String fqsfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.FQLXDH
     */
    private String fqlxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.FQGZDW
     */
    private String fqgzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SJRXM1
     */
    private String sjrxm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.GX1
     */
    private String gx1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SJRSFZH1
     */
    private String sjrsfzh1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SJRGZDW1
     */
    private String sjrgzdw1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SJRLXDG1
     */
    private String sjrlxdg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SJRXM2
     */
    private String sjrxm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.GX2
     */
    private String gx2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SJRSFZH2
     */
    private String sjrsfzh2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SJRGZDW2
     */
    private String sjrgzdw2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SJRLXDG2
     */
    private String sjrlxdg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.XJZT
     */
    private String xjzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.SSXQ
     */
    private String ssxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.XGR
     */
    private String xgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.XGSJ
     */
    private String xgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_XSXX_CZ.RKSJ
     */
    private String rksj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.BH
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.BH
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.BH
     *
     * @param bh the value for T_SHZY_JY_XSXX_CZ.BH
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.XM
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.XM
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.XM
     *
     * @param xm the value for T_SHZY_JY_XSXX_CZ.XM
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.CYM
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.CYM
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.CYM
     *
     * @param cym the value for T_SHZY_JY_XSXX_CZ.CYM
     */
    public void setCym(String cym) {
        this.cym = cym == null ? null : cym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.XB
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.XB
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.XB
     *
     * @param xb the value for T_SHZY_JY_XSXX_CZ.XB
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SFZH
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SFZH
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SFZH
     *
     * @param sfzh the value for T_SHZY_JY_XSXX_CZ.SFZH
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.MZ
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.MZ
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.MZ
     *
     * @param mz the value for T_SHZY_JY_XSXX_CZ.MZ
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.RXNF
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.RXNF
     */
    public String getRxnf() {
        return rxnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.RXNF
     *
     * @param rxnf the value for T_SHZY_JY_XSXX_CZ.RXNF
     */
    public void setRxnf(String rxnf) {
        this.rxnf = rxnf == null ? null : rxnf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.BJ
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.BJ
     */
    public String getBj() {
        return bj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.BJ
     *
     * @param bj the value for T_SHZY_JY_XSXX_CZ.BJ
     */
    public void setBj(String bj) {
        this.bj = bj == null ? null : bj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.XX
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.XX
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.XX
     *
     * @param xx the value for T_SHZY_JY_XSXX_CZ.XX
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.XJH
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.XJH
     */
    public String getXjh() {
        return xjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.XJH
     *
     * @param xjh the value for T_SHZY_JY_XSXX_CZ.XJH
     */
    public void setXjh(String xjh) {
        this.xjh = xjh == null ? null : xjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.XXXJH
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.XXXJH
     */
    public String getXxxjh() {
        return xxxjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.XXXJH
     *
     * @param xxxjh the value for T_SHZY_JY_XSXX_CZ.XXXJH
     */
    public void setXxxjh(String xxxjh) {
        this.xxxjh = xxxjh == null ? null : xxxjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.HJSZD
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.HJSZD
     */
    public String getHjszd() {
        return hjszd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.HJSZD
     *
     * @param hjszd the value for T_SHZY_JY_XSXX_CZ.HJSZD
     */
    public void setHjszd(String hjszd) {
        this.hjszd = hjszd == null ? null : hjszd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.JTXXDZ
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.JTXXDZ
     */
    public String getJtxxdz() {
        return jtxxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.JTXXDZ
     *
     * @param jtxxdz the value for T_SHZY_JY_XSXX_CZ.JTXXDZ
     */
    public void setJtxxdz(String jtxxdz) {
        this.jtxxdz = jtxxdz == null ? null : jtxxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.HJDJYZGBM
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.HJDJYZGBM
     */
    public String getHjdjyzgbm() {
        return hjdjyzgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.HJDJYZGBM
     *
     * @param hjdjyzgbm the value for T_SHZY_JY_XSXX_CZ.HJDJYZGBM
     */
    public void setHjdjyzgbm(String hjdjyzgbm) {
        this.hjdjyzgbm = hjdjyzgbm == null ? null : hjdjyzgbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SFGE
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SFGE
     */
    public String getSfge() {
        return sfge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SFGE
     *
     * @param sfge the value for T_SHZY_JY_XSXX_CZ.SFGE
     */
    public void setSfge(String sfge) {
        this.sfge = sfge == null ? null : sfge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SFCJ
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SFCJ
     */
    public String getSfcj() {
        return sfcj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SFCJ
     *
     * @param sfcj the value for T_SHZY_JY_XSXX_CZ.SFCJ
     */
    public void setSfcj(String sfcj) {
        this.sfcj = sfcj == null ? null : sfcj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SFJS
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SFJS
     */
    public String getSfjs() {
        return sfjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SFJS
     *
     * @param sfjs the value for T_SHZY_JY_XSXX_CZ.SFJS
     */
    public void setSfjs(String sfjs) {
        this.sfjs = sfjs == null ? null : sfjs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SFLSET
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SFLSET
     */
    public String getSflset() {
        return sflset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SFLSET
     *
     * @param sflset the value for T_SHZY_JY_XSXX_CZ.SFLSET
     */
    public void setSflset(String sflset) {
        this.sflset = sflset == null ? null : sflset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.MQXM
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.MQXM
     */
    public String getMqxm() {
        return mqxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.MQXM
     *
     * @param mqxm the value for T_SHZY_JY_XSXX_CZ.MQXM
     */
    public void setMqxm(String mqxm) {
        this.mqxm = mqxm == null ? null : mqxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.MQSFZH
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.MQSFZH
     */
    public String getMqsfzh() {
        return mqsfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.MQSFZH
     *
     * @param mqsfzh the value for T_SHZY_JY_XSXX_CZ.MQSFZH
     */
    public void setMqsfzh(String mqsfzh) {
        this.mqsfzh = mqsfzh == null ? null : mqsfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.MQGZDW
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.MQGZDW
     */
    public String getMqgzdw() {
        return mqgzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.MQGZDW
     *
     * @param mqgzdw the value for T_SHZY_JY_XSXX_CZ.MQGZDW
     */
    public void setMqgzdw(String mqgzdw) {
        this.mqgzdw = mqgzdw == null ? null : mqgzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.MQLXDH
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.MQLXDH
     */
    public String getMqlxdh() {
        return mqlxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.MQLXDH
     *
     * @param mqlxdh the value for T_SHZY_JY_XSXX_CZ.MQLXDH
     */
    public void setMqlxdh(String mqlxdh) {
        this.mqlxdh = mqlxdh == null ? null : mqlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.FQXM
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.FQXM
     */
    public String getFqxm() {
        return fqxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.FQXM
     *
     * @param fqxm the value for T_SHZY_JY_XSXX_CZ.FQXM
     */
    public void setFqxm(String fqxm) {
        this.fqxm = fqxm == null ? null : fqxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.FQSFZH
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.FQSFZH
     */
    public String getFqsfzh() {
        return fqsfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.FQSFZH
     *
     * @param fqsfzh the value for T_SHZY_JY_XSXX_CZ.FQSFZH
     */
    public void setFqsfzh(String fqsfzh) {
        this.fqsfzh = fqsfzh == null ? null : fqsfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.FQLXDH
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.FQLXDH
     */
    public String getFqlxdh() {
        return fqlxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.FQLXDH
     *
     * @param fqlxdh the value for T_SHZY_JY_XSXX_CZ.FQLXDH
     */
    public void setFqlxdh(String fqlxdh) {
        this.fqlxdh = fqlxdh == null ? null : fqlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.FQGZDW
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.FQGZDW
     */
    public String getFqgzdw() {
        return fqgzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.FQGZDW
     *
     * @param fqgzdw the value for T_SHZY_JY_XSXX_CZ.FQGZDW
     */
    public void setFqgzdw(String fqgzdw) {
        this.fqgzdw = fqgzdw == null ? null : fqgzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SJRXM1
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SJRXM1
     */
    public String getSjrxm1() {
        return sjrxm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SJRXM1
     *
     * @param sjrxm1 the value for T_SHZY_JY_XSXX_CZ.SJRXM1
     */
    public void setSjrxm1(String sjrxm1) {
        this.sjrxm1 = sjrxm1 == null ? null : sjrxm1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.GX1
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.GX1
     */
    public String getGx1() {
        return gx1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.GX1
     *
     * @param gx1 the value for T_SHZY_JY_XSXX_CZ.GX1
     */
    public void setGx1(String gx1) {
        this.gx1 = gx1 == null ? null : gx1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SJRSFZH1
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SJRSFZH1
     */
    public String getSjrsfzh1() {
        return sjrsfzh1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SJRSFZH1
     *
     * @param sjrsfzh1 the value for T_SHZY_JY_XSXX_CZ.SJRSFZH1
     */
    public void setSjrsfzh1(String sjrsfzh1) {
        this.sjrsfzh1 = sjrsfzh1 == null ? null : sjrsfzh1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SJRGZDW1
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SJRGZDW1
     */
    public String getSjrgzdw1() {
        return sjrgzdw1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SJRGZDW1
     *
     * @param sjrgzdw1 the value for T_SHZY_JY_XSXX_CZ.SJRGZDW1
     */
    public void setSjrgzdw1(String sjrgzdw1) {
        this.sjrgzdw1 = sjrgzdw1 == null ? null : sjrgzdw1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SJRLXDG1
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SJRLXDG1
     */
    public String getSjrlxdg1() {
        return sjrlxdg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SJRLXDG1
     *
     * @param sjrlxdg1 the value for T_SHZY_JY_XSXX_CZ.SJRLXDG1
     */
    public void setSjrlxdg1(String sjrlxdg1) {
        this.sjrlxdg1 = sjrlxdg1 == null ? null : sjrlxdg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SJRXM2
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SJRXM2
     */
    public String getSjrxm2() {
        return sjrxm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SJRXM2
     *
     * @param sjrxm2 the value for T_SHZY_JY_XSXX_CZ.SJRXM2
     */
    public void setSjrxm2(String sjrxm2) {
        this.sjrxm2 = sjrxm2 == null ? null : sjrxm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.GX2
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.GX2
     */
    public String getGx2() {
        return gx2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.GX2
     *
     * @param gx2 the value for T_SHZY_JY_XSXX_CZ.GX2
     */
    public void setGx2(String gx2) {
        this.gx2 = gx2 == null ? null : gx2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SJRSFZH2
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SJRSFZH2
     */
    public String getSjrsfzh2() {
        return sjrsfzh2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SJRSFZH2
     *
     * @param sjrsfzh2 the value for T_SHZY_JY_XSXX_CZ.SJRSFZH2
     */
    public void setSjrsfzh2(String sjrsfzh2) {
        this.sjrsfzh2 = sjrsfzh2 == null ? null : sjrsfzh2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SJRGZDW2
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SJRGZDW2
     */
    public String getSjrgzdw2() {
        return sjrgzdw2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SJRGZDW2
     *
     * @param sjrgzdw2 the value for T_SHZY_JY_XSXX_CZ.SJRGZDW2
     */
    public void setSjrgzdw2(String sjrgzdw2) {
        this.sjrgzdw2 = sjrgzdw2 == null ? null : sjrgzdw2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SJRLXDG2
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SJRLXDG2
     */
    public String getSjrlxdg2() {
        return sjrlxdg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SJRLXDG2
     *
     * @param sjrlxdg2 the value for T_SHZY_JY_XSXX_CZ.SJRLXDG2
     */
    public void setSjrlxdg2(String sjrlxdg2) {
        this.sjrlxdg2 = sjrlxdg2 == null ? null : sjrlxdg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.XJZT
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.XJZT
     */
    public String getXjzt() {
        return xjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.XJZT
     *
     * @param xjzt the value for T_SHZY_JY_XSXX_CZ.XJZT
     */
    public void setXjzt(String xjzt) {
        this.xjzt = xjzt == null ? null : xjzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.SSXQ
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.SSXQ
     */
    public String getSsxq() {
        return ssxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.SSXQ
     *
     * @param ssxq the value for T_SHZY_JY_XSXX_CZ.SSXQ
     */
    public void setSsxq(String ssxq) {
        this.ssxq = ssxq == null ? null : ssxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.XGR
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.XGR
     */
    public String getXgr() {
        return xgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.XGR
     *
     * @param xgr the value for T_SHZY_JY_XSXX_CZ.XGR
     */
    public void setXgr(String xgr) {
        this.xgr = xgr == null ? null : xgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.XGSJ
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.XGSJ
     */
    public String getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.XGSJ
     *
     * @param xgsj the value for T_SHZY_JY_XSXX_CZ.XGSJ
     */
    public void setXgsj(String xgsj) {
        this.xgsj = xgsj == null ? null : xgsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_XSXX_CZ.RKSJ
     *
     * @return the value of T_SHZY_JY_XSXX_CZ.RKSJ
     */
    public String getRksj() {
        return rksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_XSXX_CZ.RKSJ
     *
     * @param rksj the value for T_SHZY_JY_XSXX_CZ.RKSJ
     */
    public void setRksj(String rksj) {
        this.rksj = rksj == null ? null : rksj.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Student_middle)) return false;
        Student_middle that = (Student_middle) o;
        return Objects.equals(bh, that.bh) &&
                Objects.equals(xm, that.xm) &&
                Objects.equals(cym, that.cym) &&
                Objects.equals(xb, that.xb) &&
                Objects.equals(sfzh, that.sfzh) &&
                Objects.equals(mz, that.mz) &&
                Objects.equals(rxnf, that.rxnf) &&
                Objects.equals(bj, that.bj) &&
                Objects.equals(xx, that.xx) &&
                Objects.equals(xjh, that.xjh) &&
                Objects.equals(xxxjh, that.xxxjh) &&
                Objects.equals(hjszd, that.hjszd) &&
                Objects.equals(jtxxdz, that.jtxxdz) &&
                Objects.equals(hjdjyzgbm, that.hjdjyzgbm) &&
                Objects.equals(sfge, that.sfge) &&
                Objects.equals(sfcj, that.sfcj) &&
                Objects.equals(sfjs, that.sfjs) &&
                Objects.equals(sflset, that.sflset) &&
                Objects.equals(mqxm, that.mqxm) &&
                Objects.equals(mqsfzh, that.mqsfzh) &&
                Objects.equals(mqgzdw, that.mqgzdw) &&
                Objects.equals(mqlxdh, that.mqlxdh) &&
                Objects.equals(fqxm, that.fqxm) &&
                Objects.equals(fqsfzh, that.fqsfzh) &&
                Objects.equals(fqlxdh, that.fqlxdh) &&
                Objects.equals(fqgzdw, that.fqgzdw) &&
                Objects.equals(sjrxm1, that.sjrxm1) &&
                Objects.equals(gx1, that.gx1) &&
                Objects.equals(sjrsfzh1, that.sjrsfzh1) &&
                Objects.equals(sjrgzdw1, that.sjrgzdw1) &&
                Objects.equals(sjrlxdg1, that.sjrlxdg1) &&
                Objects.equals(sjrxm2, that.sjrxm2) &&
                Objects.equals(gx2, that.gx2) &&
                Objects.equals(sjrsfzh2, that.sjrsfzh2) &&
                Objects.equals(sjrgzdw2, that.sjrgzdw2) &&
                Objects.equals(sjrlxdg2, that.sjrlxdg2) &&
                Objects.equals(xjzt, that.xjzt) &&
                Objects.equals(ssxq, that.ssxq) &&
                Objects.equals(xgr, that.xgr) &&
                Objects.equals(xgsj, that.xgsj) &&
                Objects.equals(rksj, that.rksj);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bh, xm, cym, xb, sfzh, mz, rxnf, bj, xx, xjh, xxxjh, hjszd, jtxxdz, hjdjyzgbm, sfge, sfcj, sfjs, sflset, mqxm, mqsfzh, mqgzdw, mqlxdh, fqxm, fqsfzh, fqlxdh, fqgzdw, sjrxm1, gx1, sjrsfzh1, sjrgzdw1, sjrlxdg1, sjrxm2, gx2, sjrsfzh2, sjrgzdw2, sjrlxdg2, xjzt, ssxq, xgr, xgsj, rksj);
    }
}
