package com.goodsoft.society_zy.domain.entity.school;

import java.util.Objects;

/**
 * 描述:
 * 教师信息实体
 *
 * @author 严彬荣 Created on 2017-10-25 13:52
 * @version V1.0
 */
public class TeacherInfo implements java.io.Serializable {

    private static final long serialVersionUID = -6943685505683795264L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.BH
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.XM
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.XB
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.CSRQ
     */
    private String csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.SFZH
     */
    private String sfzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.ZZMM
     */
    private String zzmm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.RDNY
     */
    private String rdny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.HJDZ
     */
    private String hjdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.XZD
     */
    private String xzd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.GL
     */
    private String gl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.ZC
     */
    private String zc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.JG
     */
    private String jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.XX
     */
    private String xx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.RJKC
     */
    private String rjkc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.BGDH
     */
    private String bgdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.SJHM
     */
    private String sjhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.DYXL
     */
    private String dyxl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.ZY1
     */
    private String zy1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.ZGXL
     */
    private String zgxl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.ZY2
     */
    private String zy2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.BZ
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.SSXQ
     */
    private String ssxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.XGR
     */
    private String xgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.XGSJ
     */
    private String xgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SHZY_JY_JS.RKSJ
     */
    private String rksj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.BH
     *
     * @return the value of T_SHZY_JY_JS.BH
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.BH
     *
     * @param bh the value for T_SHZY_JY_JS.BH
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.XM
     *
     * @return the value of T_SHZY_JY_JS.XM
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.XM
     *
     * @param xm the value for T_SHZY_JY_JS.XM
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.XB
     *
     * @return the value of T_SHZY_JY_JS.XB
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.XB
     *
     * @param xb the value for T_SHZY_JY_JS.XB
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.CSRQ
     *
     * @return the value of T_SHZY_JY_JS.CSRQ
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.CSRQ
     *
     * @param csrq the value for T_SHZY_JY_JS.CSRQ
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq == null ? null : csrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.SFZH
     *
     * @return the value of T_SHZY_JY_JS.SFZH
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.SFZH
     *
     * @param sfzh the value for T_SHZY_JY_JS.SFZH
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.ZZMM
     *
     * @return the value of T_SHZY_JY_JS.ZZMM
     */
    public String getZzmm() {
        return zzmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.ZZMM
     *
     * @param zzmm the value for T_SHZY_JY_JS.ZZMM
     */
    public void setZzmm(String zzmm) {
        this.zzmm = zzmm == null ? null : zzmm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.RDNY
     *
     * @return the value of T_SHZY_JY_JS.RDNY
     */
    public String getRdny() {
        return rdny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.RDNY
     *
     * @param rdny the value for T_SHZY_JY_JS.RDNY
     */
    public void setRdny(String rdny) {
        this.rdny = rdny == null ? null : rdny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.HJDZ
     *
     * @return the value of T_SHZY_JY_JS.HJDZ
     */
    public String getHjdz() {
        return hjdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.HJDZ
     *
     * @param hjdz the value for T_SHZY_JY_JS.HJDZ
     */
    public void setHjdz(String hjdz) {
        this.hjdz = hjdz == null ? null : hjdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.XZD
     *
     * @return the value of T_SHZY_JY_JS.XZD
     */
    public String getXzd() {
        return xzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.XZD
     *
     * @param xzd the value for T_SHZY_JY_JS.XZD
     */
    public void setXzd(String xzd) {
        this.xzd = xzd == null ? null : xzd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.GL
     *
     * @return the value of T_SHZY_JY_JS.GL
     */
    public String getGl() {
        return gl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.GL
     *
     * @param gl the value for T_SHZY_JY_JS.GL
     */
    public void setGl(String gl) {
        this.gl = gl == null ? null : gl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.ZC
     *
     * @return the value of T_SHZY_JY_JS.ZC
     */
    public String getZc() {
        return zc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.ZC
     *
     * @param zc the value for T_SHZY_JY_JS.ZC
     */
    public void setZc(String zc) {
        this.zc = zc == null ? null : zc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.JG
     *
     * @return the value of T_SHZY_JY_JS.JG
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.JG
     *
     * @param jg the value for T_SHZY_JY_JS.JG
     */
    public void setJg(String jg) {
        this.jg = jg == null ? null : jg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.XX
     *
     * @return the value of T_SHZY_JY_JS.XX
     */
    public String getXx() {
        return xx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.XX
     *
     * @param xx the value for T_SHZY_JY_JS.XX
     */
    public void setXx(String xx) {
        this.xx = xx == null ? null : xx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.RJKC
     *
     * @return the value of T_SHZY_JY_JS.RJKC
     */
    public String getRjkc() {
        return rjkc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.RJKC
     *
     * @param rjkc the value for T_SHZY_JY_JS.RJKC
     */
    public void setRjkc(String rjkc) {
        this.rjkc = rjkc == null ? null : rjkc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.BGDH
     *
     * @return the value of T_SHZY_JY_JS.BGDH
     */
    public String getBgdh() {
        return bgdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.BGDH
     *
     * @param bgdh the value for T_SHZY_JY_JS.BGDH
     */
    public void setBgdh(String bgdh) {
        this.bgdh = bgdh == null ? null : bgdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.SJHM
     *
     * @return the value of T_SHZY_JY_JS.SJHM
     */
    public String getSjhm() {
        return sjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.SJHM
     *
     * @param sjhm the value for T_SHZY_JY_JS.SJHM
     */
    public void setSjhm(String sjhm) {
        this.sjhm = sjhm == null ? null : sjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.DYXL
     *
     * @return the value of T_SHZY_JY_JS.DYXL
     */
    public String getDyxl() {
        return dyxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.DYXL
     *
     * @param dyxl the value for T_SHZY_JY_JS.DYXL
     */
    public void setDyxl(String dyxl) {
        this.dyxl = dyxl == null ? null : dyxl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.ZY1
     *
     * @return the value of T_SHZY_JY_JS.ZY1
     */
    public String getZy1() {
        return zy1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.ZY1
     *
     * @param zy1 the value for T_SHZY_JY_JS.ZY1
     */
    public void setZy1(String zy1) {
        this.zy1 = zy1 == null ? null : zy1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.ZGXL
     *
     * @return the value of T_SHZY_JY_JS.ZGXL
     */
    public String getZgxl() {
        return zgxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.ZGXL
     *
     * @param zgxl the value for T_SHZY_JY_JS.ZGXL
     */
    public void setZgxl(String zgxl) {
        this.zgxl = zgxl == null ? null : zgxl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.ZY2
     *
     * @return the value of T_SHZY_JY_JS.ZY2
     */
    public String getZy2() {
        return zy2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.ZY2
     *
     * @param zy2 the value for T_SHZY_JY_JS.ZY2
     */
    public void setZy2(String zy2) {
        this.zy2 = zy2 == null ? null : zy2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.BZ
     *
     * @return the value of T_SHZY_JY_JS.BZ
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.BZ
     *
     * @param bz the value for T_SHZY_JY_JS.BZ
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.SSXQ
     *
     * @return the value of T_SHZY_JY_JS.SSXQ
     */
    public String getSsxq() {
        return ssxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.SSXQ
     *
     * @param ssxq the value for T_SHZY_JY_JS.SSXQ
     */
    public void setSsxq(String ssxq) {
        this.ssxq = ssxq == null ? null : ssxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.XGR
     *
     * @return the value of T_SHZY_JY_JS.XGR
     */
    public String getXgr() {
        return xgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.XGR
     *
     * @param xgr the value for T_SHZY_JY_JS.XGR
     */
    public void setXgr(String xgr) {
        this.xgr = xgr == null ? null : xgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.XGSJ
     *
     * @return the value of T_SHZY_JY_JS.XGSJ
     */
    public String getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.XGSJ
     *
     * @param xgsj the value for T_SHZY_JY_JS.XGSJ
     */
    public void setXgsj(String xgsj) {
        this.xgsj = xgsj == null ? null : xgsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SHZY_JY_JS.RKSJ
     *
     * @return the value of T_SHZY_JY_JS.RKSJ
     */
    public String getRksj() {
        return rksj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SHZY_JY_JS.RKSJ
     *
     * @param rksj the value for T_SHZY_JY_JS.RKSJ
     */
    public void setRksj(String rksj) {
        this.rksj = rksj == null ? null : rksj.trim();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TeacherInfo)) return false;
        TeacherInfo that = (TeacherInfo) o;
        return Objects.equals(bh, that.bh) &&
                Objects.equals(xm, that.xm) &&
                Objects.equals(xb, that.xb) &&
                Objects.equals(csrq, that.csrq) &&
                Objects.equals(sfzh, that.sfzh) &&
                Objects.equals(zzmm, that.zzmm) &&
                Objects.equals(rdny, that.rdny) &&
                Objects.equals(hjdz, that.hjdz) &&
                Objects.equals(xzd, that.xzd) &&
                Objects.equals(gl, that.gl) &&
                Objects.equals(zc, that.zc) &&
                Objects.equals(jg, that.jg) &&
                Objects.equals(xx, that.xx) &&
                Objects.equals(rjkc, that.rjkc) &&
                Objects.equals(bgdh, that.bgdh) &&
                Objects.equals(sjhm, that.sjhm) &&
                Objects.equals(dyxl, that.dyxl) &&
                Objects.equals(zy1, that.zy1) &&
                Objects.equals(zgxl, that.zgxl) &&
                Objects.equals(zy2, that.zy2) &&
                Objects.equals(bz, that.bz) &&
                Objects.equals(ssxq, that.ssxq) &&
                Objects.equals(xgr, that.xgr) &&
                Objects.equals(xgsj, that.xgsj) &&
                Objects.equals(rksj, that.rksj);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bh, xm, xb, csrq, sfzh, zzmm, rdny, hjdz, xzd, gl, zc, jg, xx, rjkc, bgdh, sjhm, dyxl, zy1, zgxl, zy2, bz, ssxq, xgr, xgsj, rksj);
    }
}
